" Plugins management {{{1
try
  packadd minpac
catch
  fun! InstallPlug() " Bootstrap plugin manager on new systems.
    silent !git clone https://github.com/k-takata/minpac.git  .vim/pack/minpac/opt/minpac
    PackUpdate
  endfun
endtry

if exists('*minpac#init')

    call minpac#init()

    call minpac#add('k-takata/minpac', { 'type': 'opt' })

    " Plugins list {{{2
    " Official LSP support {{{3

    " Completion / Linters {{{3

    " New mappings on top of basic vim functions {{{3
    " aka "Tpope's land"
    call minpac#add('junegunn/fzf.vim')

    " Snippets/Convenience {{{3

    " Git {{{3
    call minpac#add('tpope/vim-fugitive')
    call minpac#add('airblade/vim-gitgutter')

    " Vim plugin development {{{3

    " Appearance {{{3

    " Custom filetype plugins {{{3
    " 3}}}

    " Personal Packages {{{3
    " 3}}}

endif

" Minpac commands {{{2
command! PackBootstrap call InstallPlug()
command! PackUpdate packadd minpac | source $MYVIMRC | call minpac#update()
command! PackClean packadd minpac | source $MYVIMRC | call minpac#clean()

nnoremap <C-p> :<C-u>FZF<cr>

" 1}}}
